### ISSUE TITLE
Source Map Support - warning

### ISSUE THREAD

**Issue by RighteousRaichu** [2graphic/sinap-ide#142]
```
WARNING in ./~/source-map-support/source-map-support.js
    Module not found: Error: Can't resolve 'module' in '/Users/Daniel/Development/sinap-ide/node_modules/source-map-support'
    resolve 'module' in '/Users/Daniel/Development/sinap-ide/node_modules/source-map-support'
      Parsed request is a module
      using description file: /Users/Daniel/Development/sinap-ide/node_modules/source-map-support/package.json (relative path: .)
        Field 'browser' doesn't contain a valid alias configuration
      after using description file: /Users/Daniel/Development/sinap-ide/node_modules/source-map-support/package.json (relative path: .)
        resolve as module
```

**Comment by RighteousRaichu** [comment]
Also fixed by 71608fc62c30f1e4c40e9af62512008826314fa4

**Comment by Sheyne** [comment]
Doesn't appear fixed in master. Should 71608fc be merged?

**Comment by RighteousRaichu** [comment]
It is merged? And as far as I can tell it is fixed. Do you have the latest master?

**Comment by RighteousRaichu** [comment]
https://github.com/2graphic/sinap-ide/blob/master/webpack.config.js

**Comment by Sheyne** [comment]
This is the travis output for the current master. It's not fixed there. 
https://travis-ci.org/2graphic/sinap-ide/builds/203924595#L1280
